DROP DATABASE IF EXISTS createdatabase;

CREATE DATABASE createdatabase;

CREATE DATABASE createdatabase2;

CREATE DATABASE createdatabase3;

SHOW DATABASES;

DROP DATABASE IF EXISTS createdatabase2;

SHOW DATABASES;
